# Generated by Django 3.1.7 on 2021-04-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(default='default-profile.png', upload_to='profile_pics'),
        ),
    ]
