# Generated by Django 3.1.7 on 2021-04-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210417_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(default='media/default-profile.png', upload_to='media/profile_pics'),
        ),
    ]
