# Generated by Django 3.1.7 on 2021-04-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210417_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(default='default-profile.png', upload_to='profile_pics'),
        ),
    ]
